---
title: "Graphics with ggplot2"
author: "Monique Parisi"
date: "19/06/2019"
output: html_document
---

# Learning gglot2

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load the tidyverse

```{r}
library(tidyverse)
```

# Load data

```{r data}
ohi_data <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/OHI_global_data.csv")
```
```{r}
head(ohi_data)
```

```{r}
summary(ohi_data)
```

```{r}
table(ohi_data$georegion_one)
# the $ sign pulls a collumn
```

```{r}
dim(ohi_data)
```
# Create ggplot 
```{r}
ggplot(data = ohi_data, aes(x = georegion_one, y = OHI_score)) + 
  geom_jitter(width=0.2)
```
ggplot only works with data frames
aes : determines x and y variables 
+ : used to add layers 
geom : added points 
geom tells R what kind of plot 
jitter adds and random variation in the x axis 


Boxplot
```{r}
ggplot(data = ohi_data, aes (x = georegion_one)) +
  geom_bar()
```


Histogram 
```{r}
ggplot(data = ohi_data, aes(x = HDI)) + 
  geom_histogram()
```

Multiple geoms exploration
```{r multiple geoms}
ohi_summary <- read_csv ("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/OHI_scores_georegion_summary.csv")

ggplot(data=ohi_summary, aes(x = georegions, y = OHI_score_average)) +
  geom_bar(stat="identity") +
  geom_jitter(data = ohi_data, aes(x = georegion_one, y = OHI_score))
```

