---
title: "Tidy Coral"
author: "Monique Parisi"
date: "19/06/2019"
output: html_document
---

```{r setup warning=FALSE, message=FALSE}
#install libraries 
library(tidyverse) #install.packages("tidyverse")
library(janitor) #install.packages("janitor")
library(skimr) #install.packages("skimr")
library(stringr) #install.packages("stringr")

#ohi-science.org/uq-training

#data filepaths and urls
#benthic data
benthic_url <- 'https://www.nodc.noaa.gov/archive/arc0054/0104255/1.1/data/0-data/cd08/100308OaAla03m.CSV'

#buoy data
buoy_url <- 'http://www.ndbc.noaa.gov/view_text_file.php?filename=mokh1h2010.txt.gz&dir=data/historical/stdmet/'

```

#Read in benthic data

```{r benthic raw}
benthic_raw <- read_csv(benthic_url)
head(benthic_raw)
```

#Wrangle

```{r}
#wrangle time! 
benthic <- benthic_raw %>% 
  janitor::clean_names()

#explore
head(benthic)
names(benthic)

#select our columns
benthic <- benthic %>% 
  select(id_name, point, x, y, id_date) %>% 
  mutate(date = stringr::str_remove_all(id_date, "#"))

benthic
```

#Explore

```{r}
summary(benthic)

skimr::skim(benthic)

unique(benthic$date)
unique(benthic$id_name)

ggplot(benthic, aes(date, fill = id_name)) +
  geom_bar()

```

#Buoy Data!

```{r}
#import buoy data

#this doesn't work because not comma-separated! 
buoy <- readr::read_csv(buoy_url)
head(buoy)

#use read_table2
buoy_raw <- read_table2(buoy_url)
head(buoy_raw)

```

#Wrangle!

```{r}
#create a duplicate so we can edit it without having to worry about the raw data
buoy <- buoy_raw

#Step 1. overwrite column names
names(buoy) <- str_c(
  names(buoy),
  buoy %>% filter(`#YY` == "#yr"), #`` for variable name 
  sep = "_")

#looks a lot better
names(buoy)

#2. clean up slashes, get rid of '#' and "/"
names(buoy) <- str_replace_all(names(buoy), "#", "")
names(buoy) <- str_replace_all(names(buoy), "/", "")

head(buoy)

#3. delete now redundant row (because we merged row 1 and 2)
buoy <- buoy %>% 
  filter(`YY_yr` != "#yr")
head(buoy)
```

#Explore!




